import { StyleSheet } from 'react-native';
import { colors } from '../constants/Colors';

export const styles = StyleSheet.create({
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  goProButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  goProButtonText: {
    color: colors.background,
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 14,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    width: 32,
  },
  dashboardButtonIcon: {
    fontSize: 24,
    color: colors.primary,
    fontWeight: 'bold',
  },
  scrollContainer: {
    flex: 1,
  },
  sectionContainer: {
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 16,
  },
  sectionDescription: {
    fontSize: 18,
    color: colors.text,
    lineHeight: 26,
    marginBottom: 12,
  },
  sectionSubtext: {
    fontSize: 16,
    color: colors.textSecondary,
    lineHeight: 24,
    marginBottom: 30,
  },
  cardScrollContainer: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  featureCard: {
    backgroundColor: colors.surface,
    padding: 24,
    borderRadius: 16,
    marginRight: 16,
    width: 180,
    borderWidth: 1,
    borderColor: colors.border,
  },
  howToCard: {
    backgroundColor: colors.surfaceVariant,
    padding: 24,
    borderRadius: 16,
    marginRight: 16,
    width: 180,
    borderWidth: 1,
    borderColor: colors.primary + '30',
  },
  cardIcon: {
    fontSize: 32,
    marginBottom: 16,
  },
  stepNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
  },
  cardDescription: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  actionSection: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    gap: 16,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  transparentModalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalCloseText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  
  // Auth Modal Styles
  authModalContainer: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 8,
  },
  authModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  authModalSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  authInput: {
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
    marginBottom: 16,
  },
  authButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  authButtonText: {
    color: colors.onPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  authSwitchContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  authSwitchText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  authSwitchButton: {
    marginLeft: 4,
  },
  authSwitchButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },

  // Dashboard Modal Styles
  dashboardModalContainer: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
  },
  dashboardTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  dashboardSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  welcomeText: {
    fontSize: 18,
    color: colors.text,
    marginBottom: 24,
    textAlign: 'center',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
  },
  statLabel: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  upgradeButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  upgradeButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  upgradeButtonText: {
    color: colors.background,
    fontSize: 16,
    fontWeight: 'bold',
  },
  dashboardCloseButton: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  dashboardCloseText: {
    color: colors.textSecondary,
    fontSize: 16,
  },
  dashboardLogoutButton: {
    backgroundColor: '#e06d06',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  dashboardLogoutText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  proBadgeContainer: {
    backgroundColor: '#ffd700',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#ffaa00',
  },
  proBadgeText: {
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  proBadgeSubtext: {
    color: '#333333',
    fontSize: 14,
    marginTop: 4,
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  loadingText: {
    color: '#666666',
    fontSize: 16,
    marginTop: 10,
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
  },
  errorText: {
    color: '#FF6B6B',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: '#FF6B6B',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  // Photo Upload Styles
  photoUploadBox: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#ffc53a',
    borderStyle: 'dashed',
    padding: 32,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
  },
  photoUploadContent: {
  flex: 1,
  width: '100%',
  height: '100%',
  alignItems: 'center',
  justifyContent: 'center',
  },
  photoUploadIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  photoUploadTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  photoUploadSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  menuLogoContainer: {
    padding: 8,
  },
  menuLogo: {
    width: 80,
    height: 32,
  },

  // Go Pro Page styles
  goProPageContainer: {
    width: '95%',
    maxHeight: '90%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  goProPageContent: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  goProPageTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  goProPageSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 32,
  },
  pricingCard: {
    backgroundColor: colors.primary,
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 32,
  },
  pricingTitle: {
    fontSize: 18,
    color: colors.onPrimary,
    marginBottom: 8,
  },
  pricingPrice: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colors.onPrimary,
  },
  pricingPeriod: {
    fontSize: 16,
    color: colors.onPrimary,
    opacity: 0.8,
  },
  subscribeButton: {
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 24,
  },
  subscribeButtonText: {
    color: colors.background,
    fontSize: 18,
    fontWeight: 'bold',
  },
  goProPageCloseButton: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  goProPageCloseText: {
    color: colors.textSecondary,
    fontSize: 16,
  },
  
  // Splash Screen Styles
  splashContainer: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 100,
    paddingBottom: 50,
    paddingHorizontal: 20,
  },
  splashContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  splashTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 8,
    textAlign: 'center',
  },
  splashSubtitle: {
    fontSize: 18,
    color: colors.textSecondary,
    marginBottom: 60,
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
  },
  loadingDots: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  dot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary,
    marginHorizontal: 4,
  },
  dot1: {
    opacity: 0.3,
  },
  dot2: {
    opacity: 0.6,
  },
  dot3: {
    opacity: 1,
  },
  loadingText: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  splashBottom: {
    alignItems: 'center',
  },
  tagline: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: '500',
    textAlign: 'center',
  },
  
  // Ingredients Page Styles
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: colors.surface,
  },
  backButtonText: {
    fontSize: 24,
    color: colors.primary,
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
  },
  headerSpacer: {
    width: 40,
  },
  ingredientsPageContent: {
    flex: 1,
    padding: 20,
  },
  ingredientsPageTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  ingredientsPageSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  ingredientsList: {
    flex: 1,
    marginBottom: 20,
  },
  ingredientItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  ingredientText: {
    fontSize: 16,
    color: colors.text,
    flex: 1,
  },
  removeIngredientButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ff4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeIngredientText: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  addIngredientContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: colors.accent,
  },
  addIngredientInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
    paddingRight: 12,
  },
  addIngredientConfirm: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIngredientConfirmText: {
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },
  ingredientsPageBottomButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  addIngredientMainButton: {
    flex: 0.3,
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.accent,
  },
  addIngredientMainButtonText: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: 'bold',
  },
  generateRecipesButton: {
    flex: 0.6,
    backgroundColor: colors.accent,
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  generateRecipesButtonText: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
  },

  // Recipes Page Styles
  recipesPageContent: {
    flex: 1,
    padding: 20,
  },
  recipesPageTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  recipesPageSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  recipesScrollView: {
    flex: 1,
    marginBottom: 20,
  },
  recipesScrollContent: {
    paddingHorizontal: 10,
    gap: 16,
  },
  recipeCard: {
    width: 260,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  recipeImageContainer: {
    marginBottom: 12,
  },
  recipeImagePlaceholder: {
    height: 120,
    backgroundColor: colors.border,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeImageText: {
    fontSize: 40,
  },
  recipeInfo: {
    flex: 1,
  },
  recipeTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
    lineHeight: 22,
  },
  recipeMetadata: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  recipeTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  recipeTimeIcon: {
    fontSize: 14,
    marginRight: 4,
  },
  recipeTimeText: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  recipeDifficultyContainer: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  recipeDifficultyText: {
    fontSize: 12,
    color: 'white',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  recipeIngredientsPreview: {
    marginBottom: 12,
  },
  recipeIngredientsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  recipeIngredientsText: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  recipeStepsPreview: {
    marginBottom: 8,
  },
  recipeStepsTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  recipeStepsText: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  reportProblemButton: {
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  reportProblemText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '500',
  },
});
